# Generated by Django 5.1.1 on 2024-10-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_published_blogpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=2, help_text='slug', max_length=100, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
